### ISSUE TITLE
Matlab 2018a: getting error: "Warning: This widget is unsupported."

### ISSUE THREAD

**Issue by ruuddb** [StackOverflowMATLABchat/mlapptools#21] opened 2018-08-11 08:08 UTC
## Summary
Trying to set the text area type to Bold results in error in matlab2018a

## Problem Description
See the attached program, which only contains a textarea and a button
Button press should set text of the Textarea to Bold
I used:  mlapptools.fontWeight(app.TextArea, 'bold');
see:
[test.zip](https://github.com/StackOverflowMATLABchat/mlapptools/files/2280034/test.zip)

## Steps to Reproduce the Problem
Open the program in appdesigner 2018a and run it

## Specifications
  - MATLAB Release: R2018a
  - Operating System: Win10

**Comment by Dev-iL** [comment] 2018-08-11 18:14
Thanks for the report @ruuddb! Unfortunately, I cannot reproduce your problem:

![attempt](https://user-images.githubusercontent.com/6509619/43994799-72089bac-9dab-11e8-988e-77aaccc64bc0.gif)

The same happens when I'm running your `.mlapp` and clicking the button.

**Comment by Dev-iL** [comment] 2019-03-25 15:14
Closed as unreproducible.

**Closed as completed by Dev-iL** 2019-03-25 15:14 UTC
Labels: missing-info
